name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for making your first issue! This will help our team (of 2) identify problems and fix them! -Cheesidibb1"
        pr-message: "Thanks for suggesting improvements by making a pull request! Our team (of 2) are always looking for improvements and this helps a lot! -Cheesidibb1"
